CREATE DATABASE IF NOT EXISTS academia;

CREATE TABLE usuario(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    nome_usuario VARCHAR(50) NOT NULL,
    data_nascimento DATETIME NOT NULL,
    peso_usuario FLOAT NOT NULL,
    altura_usuario FLOAT NOT NULL,
    senha_usuario CHAR(32) NOT NULL,
    privilegio INT NOT NULL
);

CREATE TABLE exercicio(
	ID_EXERCICIO INT PRIMARY KEY AUTO_INCREMENT,
    nome_exercicio VARCHAR(50) NOT NULL,
    categoria_exercicio VARCHAR(50) NOT NULL,
    descricao_exercicio VARCHAR(100) NOT NULL
);

CREATE TABLE treino(
	ID_TREINO INT PRIMARY KEY AUTO_INCREMENT,
    series_treino INT NOT NULL
);

CREATE TABLE categoria(
	ID_CAREGORIA INT PRIMARY KEY AUTO_INCREMENT,
    nome_categoria VARCHAR(50) NOT NULL
);

CREATE TABLE dia_semana(
	ID_DIA INT PRIMARY KEY AUTO_INCREMENT,
    nome_dia VARCHAR(20) NOT NULL
);

ALTER TABLE treino ADD CONSTRAINT FK_EXERCICIO FOREIGN KEY (ID_EXERCICIO) REFERENCES exercicio (ID_EXERCICIO);
ALTER TABLE treino ADD CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES usuario (ID_USUARIO);
ALTER TABLE treino ADD CONSTRAINT FK_DIA FOREIGN KEY (ID_DIA) REFERENCES dia_semana (ID_DIA);
