CREATE DATABASE IF NOT EXISTS loja;

CREATE TABLE administrador(
	ID_ADM INT PRIMARY KEY AUTO_INCREMENT,
    nome_adm VARCHAR(50) NOT NULL,
    senha_adm CHAR(32) NOT NULL,
    privilegio INT NOT NULL
);

CREATE TABLE cliente(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    nome_cliente VARCHAR(50) NOT NULL,
    endereco_cliente VARCHAR(100) NOT NULL,
    senha_cliente CHAR(32) NOT NULL,
    RG_cliente CHAR(9) NOT NULL
);

CREATE TABLE produtos(
	ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    nome_produto VARCHAR(50) NOT NULL,
    preco_produto FLOAT NOT NULL,
    quantidade_produto INT NOT NULL,
    descricao_produto VARCHAR(50) NOT NULL
);

CREATE TABLE pedido(
	ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    data_pedido DATETIME NOT NULL,
    endereco_de_entrega VARCHAR(100) NOT NULL
);

CREATE TABLE categoria(
	ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    nome_categoria VARCHAR(50) NOT NULL
);

ALTER TABLE cliente ADD CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES pedido (ID_PEDIDO);
ALTER TABLE produtos ADD CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES categoria (ID_CATEGORIA);
ALTER TABLE pedido ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES cliente (ID_CLIENTE);

CREATE TABLE pedido_produto(
	ID_PEDIDO_PRODUTO INT PRIMARY KEY AUTO_INCREMENT
);

ALTER TABLE pedido_produto ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES produto (ID_PRODUTO);
ALTER TABLE pedido_produto ADD CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES pedido (ID_PEDIDO);
